import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ticketService, type Ticket, type TicketActivity, type TicketStatus, type TicketUser } from '../../services/ticket.service'
import { adminService } from '../../services/admin.service'
import { useAuth } from '../../context/AuthContext'
import { StatusBadge, PriorityBadge } from '../../components/Badges'

const statuses: TicketStatus[] = ['OPEN', 'IN_PROGRESS', 'PENDING', 'RESOLVED', 'CLOSED']
const labels: Record<TicketStatus, string> = { OPEN: 'Open', IN_PROGRESS: 'In progress', PENDING: 'Pending', RESOLVED: 'Resolved', CLOSED: 'Closed' }
const baseFor = (role: string) => role === 'MANAGER' ? '/manager' : role === 'AGENT' ? '/agent' : '/employee'

export function TicketList({ title = 'Tickets' }: { title?: string }) {
  const { user } = useAuth(); const navigate = useNavigate(); const [tickets, setTickets] = useState<Ticket[]>([]); const [error, setError] = useState('')
  useEffect(() => { ticketService.getTickets({ limit: 50 }).then(x => setTickets(x.data)).catch(() => setError('Could not load tickets.')) }, [])
  return <section><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold">{title}</h1><p className="text-sm text-slate-400">Tickets available to your role.</p></div>{user?.role === 'EMPLOYEE' && <Link className="btn-primary" to="/employee/create-ticket">New ticket</Link>}</div>{error && <p className="text-red-400">{error}</p>}<div className="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><table className="w-full text-left text-sm"><thead className="bg-slate-800/70 text-slate-400"><tr><th className="p-3">Title</th><th className="p-3">Priority</th><th className="p-3">Status</th><th className="p-3">Assignee</th></tr></thead><tbody>{tickets.map(t => <tr key={t.id} onClick={() => navigate(`${baseFor(user!.role)}/tickets/${t.id}`)} className="cursor-pointer border-t border-slate-800 hover:bg-slate-800/50"><td className="p-3 font-medium">{t.title}<div className="text-xs text-slate-500">{t.category}</div></td><td className="p-3"><PriorityBadge priority={t.priority} /></td><td className="p-3"><StatusBadge status={t.status} /></td><td className="p-3 text-slate-400">{t.assignee?.name ?? 'Unassigned'}</td></tr>)}</tbody></table>{!tickets.length && <p className="p-8 text-center text-slate-400">No tickets found.</p>}</div></section>
}

export function TicketDetails() {
  const { id } = useParams(); const { user } = useAuth(); const [ticket, setTicket] = useState<Ticket | null>(null); const [activities, setActivities] = useState<TicketActivity[]>([]); const [agents, setAgents] = useState<TicketUser[]>([]); const [comment, setComment] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const load = async () => { if (!id) return; try { const [t, a] = await Promise.all([ticketService.getTicketById(id), ticketService.getActivities(id)]); setTicket(t); setActivities(a); if (user?.role === 'MANAGER') setAgents(await adminService.agents()) } catch { setError('Could not load this ticket.') } }
  useEffect(() => { void load() }, [id, user?.role])
  const act = async (work: () => Promise<unknown>) => { setBusy(true); setError(''); try { await work(); await load() } catch (e: any) { setError(e.response?.data?.message ?? 'Update failed.') } finally { setBusy(false) } }
  if (!ticket) return <p className="text-slate-400">{error || 'Loading ticket...'}</p>
  const canUpdate = user?.role === 'MANAGER' || (user?.role === 'AGENT' && ticket.assignee?.id === user.id)
  return <section className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-5"><Link to={`${baseFor(user!.role)}/tickets`} className="text-sm text-indigo-300">← Back to tickets</Link><article className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="mb-4 flex flex-wrap gap-2"><StatusBadge status={ticket.status} /><PriorityBadge priority={ticket.priority} /></div><h1 className="text-2xl font-bold">{ticket.title}</h1><p className="mt-3 whitespace-pre-wrap text-slate-300">{ticket.description}</p><div className="mt-5 text-sm text-slate-400">Requested by {ticket.requester.name} · {new Date(ticket.createdAt).toLocaleString()}</div></article><article className="rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Activity</h2><div className="mt-4 space-y-4">{activities.map(a => <div key={a.id} className="border-l-2 border-slate-700 pl-3"><p className="text-sm"><span className="font-medium">{a.user.name}</span> <span className="text-slate-400">{a.message}</span></p><p className="text-xs text-slate-500">{new Date(a.createdAt).toLocaleString()}</p></div>)}</div><form onSubmit={e => { e.preventDefault(); if (comment.trim()) void act(() => ticketService.addComment(ticket.id, comment).then(() => setComment(''))) }} className="mt-5 flex gap-2"><input value={comment} onChange={e => setComment(e.target.value)} className="input-field" placeholder="Add a comment" /><button disabled={busy} className="btn-primary">Send</button></form></article></div><aside className="space-y-4 rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Ticket controls</h2><p className="text-sm text-slate-400">Assigned to: {ticket.assignee?.name ?? 'Unassigned'}</p>{user?.role === 'AGENT' && !ticket.assignee && <button disabled={busy} onClick={() => void act(() => ticketService.assignToSelf(ticket.id))} className="btn-primary w-full">Claim ticket</button>}{user?.role === 'MANAGER' && <select value={ticket.assignee?.id ?? ''} onChange={e => e.target.value && void act(() => ticketService.assignToAgent(ticket.id, e.target.value))} className="input-field"><option value="">Assign an agent…</option>{agents.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select>}{canUpdate && <label className="block text-sm text-slate-300">Status<select value={ticket.status} onChange={e => void act(() => ticketService.updateTicket(ticket.id, { status: e.target.value as TicketStatus }))} className="input-field mt-1">{statuses.map(s => <option key={s} value={s}>{labels[s]}</option>)}</select></label>}{error && <p className="text-sm text-red-400">{error}</p>}</aside></section>
}
